name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Build Image
      run: make image
    - name: Compile
      run: make resume
    - uses: actions/upload-artifact@master
      with:
        name: Resume
        path: ./resume.pdf
