name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install LaTeX
      run: sudo apt-get install texlive-latex-base texlive-latex-extra texlive-fonts-recommended latexmk
    - name: Compile
      run: make metal
    - uses: actions/upload-artifact@master
      with:
        name: Resume
        path: ./resume.pdf
